-- 네이버 검색광고 일별 리포트 저장 + 관리자 조회 정책
-- Supabase SQL Editor에서 1회 실행하거나 배포 파이프라인의 migration으로 적용합니다.

create table if not exists public.naver_sa_daily_reports (
  id bigint generated by default as identity primary key,
  report_date date not null,
  customer_id text not null,
  totals jsonb not null default '{}'::jsonb,
  campaigns jsonb not null default '[]'::jsonb,
  recommendations jsonb not null default '[]'::jsonb,
  keyword_ideas jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (report_date, customer_id)
);

comment on table public.naver_sa_daily_reports is '네이버 검색광고 API 일별 성과와 운영 제안';

create index if not exists naver_sa_daily_reports_customer_date_idx
  on public.naver_sa_daily_reports (customer_id, report_date desc);

alter table public.naver_sa_daily_reports enable row level security;

revoke all on public.naver_sa_daily_reports from anon;
revoke all on public.naver_sa_daily_reports from authenticated;
grant select on public.naver_sa_daily_reports to authenticated;

drop policy if exists "Admins can read Naver SA reports" on public.naver_sa_daily_reports;
create policy "Admins can read Naver SA reports"
  on public.naver_sa_daily_reports
  for select
  to authenticated
  using (private.is_admin_user());
